# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: phont_msg.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fphont_msg.proto\x12\x05Phone\"\x94\x01\n\x05Phone\x12\x11\n\ttimestamp\x18\x01 \x01(\x02\x12\x11\n\tcolor_img\x18\x02 \x01(\x0c\x12\x11\n\tdepth_img\x18\x03 \x01(\x0c\x12\x13\n\x0b\x64\x65pth_width\x18\x04 \x01(\x05\x12\x14\n\x0c\x64\x65pth_height\x18\x05 \x01(\x05\x12\x12\n\nlocal_pose\x18\x06 \x03(\x02\x12\x13\n\x0bglobal_pose\x18\x07 \x03(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'phont_msg_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PHONE']._serialized_start=27
  _globals['_PHONE']._serialized_end=175
# @@protoc_insertion_point(module_scope)
